# Generated by Django 3.1 on 2020-08-29 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learncodex', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DropboxToken',
        ),
    ]
