# Generated by Django 3.1 on 2020-08-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learncodex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freecourse',
            old_name='title_dics',
            new_name='discription',
        ),
        migrations.AddField(
            model_name='freelesson',
            name='slug',
            field=models.SlugField(default='qwerty', max_length=650, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freelesson',
            name='title',
            field=models.CharField(max_length=600),
        ),
    ]
