# Generated by Django 3.1 on 2020-08-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learncodex', '0002_auto_20200807_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freecourse',
            name='content',
        ),
    ]
